const express = require('express');
const router = express.Router();

const serversRouter = require('./servers.route');
const botRouter = require('./bot.route');
const botTypeRouter = require('./botType.route');
const userRouter = require('./user.route');
const authRouter = require('./auth.route');
const configByBitV1FuturesRouter = require('./Configs/ByBit/V1/futures.route');
const configOKXV1FuturesRouter = require('./Configs/OKX/V1/futures.route');
const configByBitV3Router = require('./Configs/ByBit/V3/config.route');
const waveByBitV3Router = require('./Configs/ByBit/V3/wave.route');
const configByBitV3VIPRouter = require('./Configs/ByBit/V3/configVIP.route');
const configBinanceV3VIPRouter = require('./Configs/Binance/V3/configVIP.route');
const configOKXV3VIPRouter = require('./Configs/OKX/V3/configV.route');
const configBinanceV3Router = require('./Configs/Binance/V3/config.route');
const configBinanceOldV3Router = require('./Configs/Binance/V3/configOld.route');
const roleRouter = require('./role.route');
const groupRouter = require('./group.route');
const positionBinanceRouter = require('./Positions/Binance/position.route');
const positionByBitV3Router = require('./Positions/ByBit/V3/position.route');
const positionByBitV1Router = require('./Positions/ByBit/V1/position.route');
const positionOKXV1Router = require('./Positions/OKX/V1/position.route');
const spotByBitRouter = require('./Configs/ByBit/V1/spot.route');
const spotOKXRouter = require('./Configs/OKX/V1/spot.route');
const marginByBitRouter = require('./Configs/ByBit/V1/margin.route');
const marginOKXRouter = require('./Configs/OKX/V1/margin.route');
const scannerByBitV1Router = require('./Configs/ByBit/V1/scanner.route');
const scannerOKXV1Router = require('./Configs/OKX/V1/scanner.route');
const scannerByBitV1VRouter = require('./Configs/ByBit/V1/scannerV.route');
const scannerOKXV1VRouter = require('./Configs/OKX/V1/scannerV.route');
const scannerByBitV3Router = require('./Configs/ByBit/V3/scanner.route');
const scannerBinanceV3Router = require('./Configs/Binance/V3/scanner.route');
const coinRouter = require('./Coins/ByBit/coinFutures.route');
const groupCoinByBitV3Router = require('./Coins/ByBit/groupCoinV3.route');
const coinBinanceRouter = require('./Coins/Binance/coin.route');
const groupCoinBinanceRouter = require('./Coins/Binance/groupCoin.route');
const coinByBitRouter = require('./Coins/ByBit/coin.route');
const coinByBitFuturesRouter = require('./Coins/ByBit/coinFutures.route');
const coinOKXV1Router = require('./Coins/OKX/coin.route');
const coinOKXV1FuturesRouter = require('./Coins/OKX/coinFutures.route');
const ordersOKXV1Router = require('./Orders/OKX/orders.route');
const ordersBinanceRouter = require('./Orders/Binance/orders.route');
const ordersByBitRouter = require('./Orders/ByBit/orders.route');
const configOKXV3Router = require('./Configs/OKX/V3/config.route');
const scannerOKXV3Router = require('./Configs/OKX/V3/scanner.route');
const groupCoinOKXV3Router = require('./Coins/OKX/groupCoinV3.route');
const configMT5V4Router = require('./Configs/MT5/V4/config.route');
const coinsBlockRouter = require('./CoinsBlock/coinsBlock.route');

router.use('/auth', authRouter);
router.use('/servers', serversRouter);
router.use('/user', userRouter);
router.use('/bot', botRouter);
router.use('/botType', botTypeRouter);
router.use('/configByBitV1Futures', configByBitV1FuturesRouter);
router.use('/configOKXV1Futures', configOKXV1FuturesRouter);
router.use('/configByBitV3', configByBitV3Router);
router.use('/waveByBitV3', waveByBitV3Router);
router.use('/configByBitV3VIP', configByBitV3VIPRouter);
router.use('/configBinanceV3VIP', configBinanceV3VIPRouter);
router.use('/configOKXV3V', configOKXV3VIPRouter);
router.use('/configBinanceV3', configBinanceV3Router);
router.use('/configBinanceOldV3', configBinanceOldV3Router);
router.use('/spotByBit', spotByBitRouter);
router.use('/spotOKX', spotOKXRouter);
router.use('/marginByBit', marginByBitRouter);
router.use('/marginOKX', marginOKXRouter);
router.use('/role', roleRouter);
router.use('/group', groupRouter);
router.use('/positionBinance', positionBinanceRouter);
router.use('/positionByBitV3', positionByBitV3Router);
router.use('/positionByBitV1', positionByBitV1Router);
router.use('/positionOKXV1', positionOKXV1Router);
router.use('/scannerByBitV1', scannerByBitV1Router);
router.use('/scannerByBitV1V', scannerByBitV1VRouter);
router.use('/scannerOKXV1', scannerOKXV1Router);
router.use('/scannerOKXV1V', scannerOKXV1VRouter);
router.use('/scannerByBitV3', scannerByBitV3Router);
router.use('/scannerBinanceV3', scannerBinanceV3Router);
router.use('/coin', coinRouter);
router.use('/coinsBlock', coinsBlockRouter);
router.use('/groupCoinByBitV3', groupCoinByBitV3Router);
router.use('/coinBinanceFutures', coinBinanceRouter);
router.use('/groupCoinBinance', groupCoinBinanceRouter);
router.use('/coinByBit', coinByBitRouter);
router.use('/coinByBitFutures', coinByBitFuturesRouter);
router.use('/coinOKX', coinOKXV1Router);
router.use('/coinOKXFutures', coinOKXV1FuturesRouter);
router.use('/ordersOKX', ordersOKXV1Router);
router.use('/ordersByBit', ordersByBitRouter);
router.use('/ordersBinance', ordersBinanceRouter);
router.use('/configOKXV3', configOKXV3Router);
router.use('/scannerOKXV3', scannerOKXV3Router);
router.use('/groupCoinOKXV3', groupCoinOKXV3Router);
router.use('/configMT5V4', configMT5V4Router);

// Sử dụng các route khác tương tự

module.exports = router;
